In [1]:
import io
import requests
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/virtualdvid/Statistics/master/data/EGM_Lectores.csv'
file = requests.get(url).text

In [3]:
df = pd.read_csv(io.StringIO(file), skiprows=4, header=1)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"EGM Colombia , 1a ola de 2011","EGM Colombia , 2a ola de 2011","EGM Colombia , 3a ola de 2011","EGM Colombia , 1a ola de 2012","EGM Colombia , 2a ola de 2012","EGM Colombia , 3a ola de 2012",...,"EGM Colombia , 2a ola de 2014","EGM Colombia , 3a ola de 2014","EGM Colombia , 1a ola de 2015","EGM Colombia , 2a ola de 2015","EGM Colombia , 3a ola de 2015","EGM Colombia , 1a ola de 2016","EGM Colombia , 2a ola de 2016","EGM Colombia , 3a ola de 2016","EGM Colombia , 1a ola de 2017","EGM Colombia , 2a ola de 2017"
0,CIUDAD,Bogota,Total,NaN,7577,9253,9289,6636,6929,8337,...,6130,6704,7915,6686,6752,7595,9226,7818,8199,9495
1,NaN,NaN,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Tiempo,456,884,957,638,232,195,...,638,267,608,511,650,657,685,433,932,703
2,NaN,NaN,NaN,El Espectador,798,622,666,972,473,462,...,105,971,163,424,462,338,634,911,910,719
3,NaN,NaN,AUDIENCIA ULTIMO PERIODO DE REVISTAS SEMANALES,Revista Semana,413,929,991,104,429,761,...,764,994,291,247,869,735,499,756,506,522
4,NaN,NaN,AUDIENCIA ULTIMO PERIODO DE REVISTAS QUINCENALES,TV y Novelas,755,355,218,419,913,710,...,440,124,659,210,661,976,270,323,845,583

In [4]:
df.iloc[:,0:3] = df.iloc[:,0:3].fillna(value=None, method='ffill')
df.iloc[:,3:4] = df.iloc[:,3:4].fillna('PoblaciÃ³n')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"EGM Colombia , 1a ola de 2011","EGM Colombia , 2a ola de 2011","EGM Colombia , 3a ola de 2011","EGM Colombia , 1a ola de 2012","EGM Colombia , 2a ola de 2012","EGM Colombia , 3a ola de 2012",...,"EGM Colombia , 2a ola de 2014","EGM Colombia , 3a ola de 2014","EGM Colombia , 1a ola de 2015","EGM Colombia , 2a ola de 2015","EGM Colombia , 3a ola de 2015","EGM Colombia , 1a ola de 2016","EGM Colombia , 2a ola de 2016","EGM Colombia , 3a ola de 2016","EGM Colombia , 1a ola de 2017","EGM Colombia , 2a ola de 2017"
0,CIUDAD,Bogota,Total,PoblaciÃ³n,7577,9253,9289,6636,6929,8337,...,6130,6704,7915,6686,6752,7595,9226,7818,8199,9495
1,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Tiempo,456,884,957,638,232,195,...,638,267,608,511,650,657,685,433,932,703
2,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Espectador,798,622,666,972,473,462,...,105,971,163,424,462,338,634,911,910,719
3,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS SEMANALES,Revista Semana,413,929,991,104,429,761,...,764,994,291,247,869,735,499,756,506,522
4,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS QUINCENALES,TV y Novelas,755,355,218,419,913,710,...,440,124,659,210,661,976,270,323,845,583

In [5]:
df.rename(columns={df.columns[0]: "CatDemog",
                   df.columns[1]: "Demog",
                   df.columns[2]: "MediciÃ³n",
                   df.columns[3]: "Vehiculo"}, inplace = True)
df.head(0)

Empty DataFrame
Columns: [CatDemog, Demog, MediciÃ³n, Vehiculo, EGM Colombia , 1a ola de 2011, EGM Colombia , 2a ola de 2011, EGM Colombia , 3a ola de 2011, EGM Colombia , 1a ola de 2012, EGM Colombia , 2a ola de 2012, EGM Colombia , 3a ola de 2012, EGM Colombia , 2a ola de 2013, EGM Colombia , 3a ola de 2013, EGM Colombia , 1a ola de 2014, EGM Colombia , 2a ola de 2014, EGM Colombia , 3a ola de 2014, EGM Colombia , 1a ola de 2015, EGM Colombia , 2a ola de 2015, EGM Colombia , 3a ola de 2015, EGM Colombia , 1a ola de 2016, EGM Colombia , 2a ola de 2016, EGM Colombia , 3a ola de 2016, EGM Colombia , 1a ola de 2017, EGM Colombia , 2a ola de 2017]
Index: []

[0 rows x 23 columns]

In [6]:
df2 = pd.melt(df, id_vars=list(df.columns)[:4], value_vars=list(df.columns)[4:], var_name='Ola', value_name='Lectores')
df2.head()

,CatDemog,Demog,MediciÃ³n,Vehiculo,Ola,Lectores
0,CIUDAD,Bogota,Total,PoblaciÃ³n,"EGM Colombia , 1a ola de 2011",7577
1,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Tiempo,"EGM Colombia , 1a ola de 2011",456
2,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Espectador,"EGM Colombia , 1a ola de 2011",798
3,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS SEMANALES,Revista Semana,"EGM Colombia , 1a ola de 2011",413
4,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS QUINCENALES,TV y Novelas,"EGM Colombia , 1a ola de 2011",755

In [7]:
df2.iloc[:,4:5] = df2['Ola'].str.split().str.get(6) + '-' + df2['Ola'].str.split().str.get(3).str.replace('a','')
df2.iloc[:,5:6] = df2['Lectores'] * 1000
df2['Filtro'] = "Lectores"
df2.head()

,CatDemog,Demog,MediciÃ³n,Vehiculo,Ola,Lectores,Filtro
0,CIUDAD,Bogota,Total,PoblaciÃ³n,2011-1,7577000,Lectores
1,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Tiempo,2011-1,456000,Lectores
2,CIUDAD,Bogota,AUDIENCIA DE DIARIOS ULTIMO PERIODO,El Espectador,2011-1,798000,Lectores
3,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS SEMANALES,Revista Semana,2011-1,413000,Lectores
4,CIUDAD,Bogota,AUDIENCIA ULTIMO PERIODO DE REVISTAS QUINCENALES,TV y Novelas,2011-1,755000,Lectores

In [8]:
df2.to_csv('EGM2016.csv', sep=',', encoding='utf-8')